[package]
name = "bbl-ingest"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dsp = { workspace = true }
blackbox-log = { workspace = true }
blake3 = { workspace = true }
tracing = { workspace = true }
domain = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
