//! ArduPilot MAVLink client: parameters (typed PARAM_SET + read-back verify),
//! DataFlash log download (LOG_REQUEST_* in 90-byte LOG_DATA chunks, resumable),
//! status from HEARTBEAT / AUTOPILOT_VERSION, and the `domain::fc::FlightController`
//! implementation the wizard drives.
//!
//! Protocol facts are pinned to ArduPilot source (`libraries/GCS_MAVLink/GCS_Param.cpp`,
//! `libraries/AP_Logger/AP_Logger_MAVLinkLogTransfer.cpp`, `GCS_Common.cpp`) and
//! the message definitions generated by the `mavlink` crate from `common.xml`.

pub mod client;
pub mod link;
pub mod logs;
pub mod mock;
pub mod params;

pub use client::MavClient;
pub use link::{Link, SerialLink, TcpLink};
pub use mavlink::dialects::ardupilotmega as apm;
pub use params::{Param, ParamStore};

/// Local (GCS-side) MAVLink identity used on every message we send.
pub const GCS_SYSTEM_ID: u8 = 255;
pub const GCS_COMPONENT_ID: u8 = 190; // MAV_COMP_ID_MISSIONPLANNER (common.xml), what GCS tools use
