#!/usr/bin/env python3
"""Generate crates/recommend/src/ap_param_meta.rs from ArduPilot's apm.pdef.xml
(https://autotest.ardupilot.org/Parameters/ArduCopter/apm.pdef.xml).
Only parameter groups the tuner may touch are kept."""
import re, sys, xml.etree.ElementTree as ET

PREFIXES = ("ATC_", "INS_", "LOG_", "MOT_", "AUTOTUNE_", "SCHED_", "FFT_", "PSC_", "PILOT_", "FILT", "ANGLE_MAX", "ACRO_", "FRAME_")

def main(src, dst):
    root = ET.parse(src).getroot()
    rows = {}
    for p in root.iter("param"):
        name = p.get("name", "")
        name = name.split(":")[-1]  # "ArduCopter:XYZ" -> XYZ
        if not name.startswith(PREFIXES):
            continue
        rng = None; inc = None; reboot = False; units = ""
        values = []
        for f in p.findall("field"):
            n = f.get("name"); t = (f.text or "").strip()
            if n == "Range":
                parts = t.replace(",", " ").split()
                if len(parts) >= 2:
                    try: rng = (float(parts[0]), float(parts[1]))
                    except ValueError: pass
            elif n == "Increment":
                try: inc = float(t)
                except ValueError: pass
            elif n == "RebootRequired":
                reboot = t.lower() == "true"
            elif n == "Units":
                units = t
        if "reboot" in (p.get("documentation") or "").lower() and "takes effect on the next reboot" in (p.get("documentation") or "").lower():
            reboot = True
        for v in p.findall("values/value"):
            values.append(v.get("code"))
        has_bitmask = p.find("bitmask") is not None
        rows[name] = (rng, inc, reboot, units, bool(values), has_bitmask)
    names = sorted(rows)
    out = []
    out.append("//! GENERATED by scripts/gen_ap_param_meta.py from ArduPilot apm.pdef.xml — do not edit.")
    out.append("//! Source: https://autotest.ardupilot.org/Parameters/ArduCopter/apm.pdef.xml")
    out.append("")
    out.append("#[derive(Debug, Clone, Copy, PartialEq)]")
    out.append("pub struct ParamMeta {")
    out.append("    pub name: &'static str,")
    out.append("    pub min: Option<f32>,")
    out.append("    pub max: Option<f32>,")
    out.append("    pub increment: Option<f32>,")
    out.append("    pub reboot_required: bool,")
    out.append("    pub units: &'static str,")
    out.append("    /// Enumerated values or bitmask: treat as integer.")
    out.append("    pub integer: bool,")
    out.append("}")
    out.append("")
    out.append("pub static AP_PARAM_META: &[ParamMeta] = &[")
    def f(x): return "None" if x is None else f"Some({x!r}f32)".replace("f32","").replace("Some(", "Some(") and f"Some({float(x)})"
    for n in names:
        rng, inc, reboot, units, has_values, has_bitmask = rows[n]
        mn = f"Some({rng[0]})" if rng else "None"
        mx = f"Some({rng[1]})" if rng else "None"
        ic = f"Some({inc})" if inc is not None else "None"
        integer = "true" if (has_values or has_bitmask) else "false"
        out.append(f'    ParamMeta {{ name: "{n}", min: {mn}, max: {mx}, increment: {ic}, reboot_required: {str(reboot).lower()}, units: "{units}", integer: {integer} }},')
    out.append("];")
    out.append("")
    out.append("pub fn lookup(name: &str) -> Option<&'static ParamMeta> {")
    out.append("    AP_PARAM_META.binary_search_by(|m| m.name.cmp(name)).ok().map(|i| &AP_PARAM_META[i])")
    out.append("}")
    open(dst, "w").write("\n".join(out) + "\n")
    print(dst, len(names), "params")

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
