[package]
name = "fc-mavlink"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
domain = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serialport = "4.7"
mavlink = { version = "0.18", default-features = false, features = ["std", "dialect-ardupilotmega"] }

[dev-dependencies]
uuid = { workspace = true }

